# Generated by Django 2.1.8 on 2019-05-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredintes',
            field=models.ManyToManyField(to='core.Ingrediente'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
